[2023-04-26 09:41:51,317] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_email_notification.email_notification manual__2023-04-26T09:41:49.805317+00:00 [queued]>
[2023-04-26 09:41:51,323] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_email_notification.email_notification manual__2023-04-26T09:41:49.805317+00:00 [queued]>
[2023-04-26 09:41:51,324] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-26 09:41:51,324] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-04-26 09:41:51,325] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-26 09:41:51,332] {taskinstance.py:1377} INFO - Executing <Task(EmailOperator): email_notification> on 2023-04-26 09:41:49.805317+00:00
[2023-04-26 09:41:51,336] {standard_task_runner.py:52} INFO - Started process 70 to run task
[2023-04-26 09:41:51,340] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_email_notification', 'email_notification', 'manual__2023-04-26T09:41:49.805317+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/sample_dag.py', '--cfg-path', '/tmp/tmp4jhz5n40', '--error-file', '/tmp/tmpn_iugw_m']
[2023-04-26 09:41:51,341] {standard_task_runner.py:80} INFO - Job 3: Subtask email_notification
[2023-04-26 09:41:51,379] {task_command.py:370} INFO - Running <TaskInstance: example_email_notification.email_notification manual__2023-04-26T09:41:49.805317+00:00 [running]> on host d2b8b31c4ef1
[2023-04-26 09:41:51,424] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_email_notification
AIRFLOW_CTX_TASK_ID=email_notification
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T09:41:49.805317+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T09:41:49.805317+00:00
[2023-04-26 09:41:51,433] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-04-26 09:41:51,434] {configuration.py:549} WARNING - section/key [smtp/smtp_user] not found in config
[2023-04-26 09:41:51,434] {email.py:228} INFO - Email alerting: attempt 1
[2023-04-26 09:41:51,435] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 85, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-04-26 09:41:51,443] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=example_email_notification, task_id=email_notification, execution_date=20230426T094149, start_date=20230426T094151, end_date=20230426T094151
[2023-04-26 09:41:51,449] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task email_notification ([Errno 99] Cannot assign requested address; 70)
[2023-04-26 09:41:51,473] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-04-26 09:41:51,495] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
